[build]
base = "apps/web"
command = """
cd ../..
pnpm install
npx prisma generate
pnpm run build:web
"""
publish = "apps/web/dist"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client"]
directory = "apps/web/netlify/functions"

[dev]
framework = "#custom"
command = "pnpm run dev"
targetPort = 5173
port = 8888
publish = "dist"
autoLaunch = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
