[build]
base = "apps/web"
publish = "dist"
functions = "netlify/functions"

[build]
command = "npm run prisma:generate && npm run build"

[dev]
framework = "#custom"
command = "npx vite"
targetPort = 5173
port = 9999

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client"]
