[build]
base = "apps/web"
command = """
cd ../..
pnpm install
cd apps/web
npx prisma generate
cd ../..
pnpm run build:web
"""
publish = "dist"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client"]

[dev]
framework = "#custom"
command = "pnpm run dev"
targetPort = 5173
port = 8888
publish = "dist"
autoLaunch = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
